sudo: required
services:
    - docker

before_install:
    - docker build -t radonjaprelevic/react-test -f./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true radonjaprelevic/react-test npm test

after_success:
    - docker build -t radonjaprelevic/multi-client ./client
    - docker build -t radonjaprelevic/multi-nginx ./nginx
    - docker build -t radonjaprelevic/multi-server ./server
    - docker build -t radonjaprelevic/multi-worker ./worker
    # Log in to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push radonjaprelevic/multi-client
    - docker push radonjaprelevic/multi-nginx
    - docker push radonjaprelevic/multi-server
    - docker push radonjaprelevic/multi-worker